"""create_table_users

Revision ID: 39698e90eba5
Revises: 
Create Date: 2023-01-19 15:58:19.156481

"""
from alembic import op
import sqlalchemy as sa
from models.index import Role
import datetime

# revision identifiers, used by Alembic.
revision = '39698e90eba5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer, primary_key=True, index=True),
                    sa.Column('email', sa.String(255),
                              unique=True, index=True),
                    sa.Column('username', sa.String(255), index=True),
                    sa.Column('password', sa.String(255), index=True),
                    sa.Column('role', sa.Enum(Role),
                              default=Role.user, index=True),
                    sa.Column('created_at', sa.DateTime,
                              default=datetime.datetime.now()),
                    sa.Column('updated_at', sa.DateTime,
                              default=datetime.datetime.now, onupdate=datetime.datetime.now)
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
